version: 2
updates:
  - package-ecosystem: "npm"  # Cambia según el ecosistema de tu proyecto
    directory: "/"              # Ruta del directorio del proyecto
    schedule:
      interval: "weekly"
